baseURL = "https://gilbertsanchez.com/"
title = "Hey! It's Gilbert!"
defaultContentLanguage = "en"
#theme = "congo"
timeZone = "UTC"

timeout = "60s"

enableRobotsTXT = true
pagination.pagerSize = 10

summaryLength = 0

disqusShortname = "gilbertsanchez" 
#googleAnalytics = "G-CWJLL32MYW"

[taxonomies]
  series = "series"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
