baseURL = "https://gilbertsanchez.com/"
title = "Hey! It's Gilbert!"
defaultContentLanguage = "en"
#theme = "congo"
timeZone = "UTC"

timeout = "60s"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

disqusShortname = "gilbertsanchez" 
#googleAnalytics = "G-CWJLL32MYW"

[taxonomies]
  posts = "posts"
  series = "series"
  tag = "tags"
  note = "notes"

[outputs]
  home = ["HTML", "RSS", "JSON"]
