disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Hey! It's Gilbert!"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "profile.png"

[params.author]
name = "Gilbert Sanchez"
image = "profile.png"
headline = "Not just good. Good enough."
bio = "Not just good. Good enough."
links = [
#   { email = "mailto:hello@your_domain.com" },
{ link = "https://links.gilbertsanchez.com/" },
#   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#   { apple = "https://www.apple.com" },
#   { blogger = "https://username.blogspot.com/" },
{ bluesky = "https://bsky.app/profile/gilbertsanchez.com" },
#   { codepen = "https://codepen.io/username" },
#   { dev = "https://dev.to/username" },
#   { discord = "https://discord.gg/invitecode" },
#   { dribbble = "https://dribbble.com/username" },
  { facebook = "https://facebook.com/HeyItsGilbert" },
#   { flickr = "https://www.flickr.com/photos/username/" },
#   { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/HeyItsGilbert" },
#   { gitlab = "https://gitlab.com/username" },
#   { google = "https://www.google.com/" },
#   { hashnode = "https://username.hashnode.dev" },
  { instagram = "https://instagram.com/gilbertsanchez" },
#   { keybase = "https://keybase.io/username" },
#   { kickstarter = "https://www.kickstarter.com/profile/username" },
#   { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://linkedin.com/in/gilbertsanchez" },
  { mastodon = "https://fosstodon.org/@HeyItsGilbert" },
#   { medium = "https://medium.com/username" },
#   { microsoft = "https://www.microsoft.com/" },
#   { orcid = "https://orcid.org/userid" },
#   { patreon = "https://www.patreon.com/username" },
#   { pinterest = "https://pinterest.com/username" },
#   { reddit = "https://reddit.com/user/username" },
#   { researchgate = "https://www.researchgate.net/profile/username" },
#   { slack = "https://workspace.url/team/userid" },
#   { snapchat = "https://snapchat.com/add/username" },
#   { soundcloud = "https://soundcloud.com/username" },
#   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#   { steam = "https://steamcommunity.com/profiles/userid" },
#   { telegram = "https://t.me/username" },
#   { tiktok = "https://tiktok.com/@username" },
#   { tumblr = "https://username.tumblr.com" },
#   { twitch = "https://twitch.tv/username" },
  { twitter = "https://twitter.com/HeyItsGilbertS" },
#   { whatsapp = "https://wa.me/phone-number" },
#   { youtube = "https://youtube.com/username" },
]