[[main]]
none = "none"

[[main]]
name = ":newspaper:Posts"
pageRef = "posts"
identifier = "81PNQBduNI"
weight = 1

[[main]]
name = ":seedling: Notes"
url = "https://garden.gilbertsanchez.com/"
identifier = "yCv4RCmvLj"
weight = 2

[[main]]
name = ":notebook: Projects"
pageRef = "projects"
identifier = "Zqhlk2ZASq"
weight = 3

[[main]]
name = ":technologist: Presentations"
pageRef = "presentations"
identifier = "dajioPsoJd"
weight = 4

[[main]]
name = ":label: Tags"
pageRef = "tags"
identifier = "vHqD2oFFMh"
weight = 5

[[main]]
name = ":newspaper_roll: RSS"
pageRef = "index.xml"
identifier = "zNh9Tjq8MD"
weight = 6

[[footer]]
none = "none"

[[footer]]
name = ":newspaper:Posts"
pageRef = "posts"
identifier = "81PNQBduNI"
weight = 1

[[footer]]
name = ":seedling: Notes"
url = "https://garden.gilbertsanchez.com/"
identifier = "yCv4RCmvLj"
weight = 2

[[footer]]
name = ":notebook: Projects"
pageRef = "projects"
identifier = "Zqhlk2ZASq"
weight = 3

[[footer]]
name = ":technologist: Presentations"
pageRef = "presentations"
identifier = "dajioPsoJd"
weight = 4

[[footer]]
name = ":label: Tags"
pageRef = "tags"
identifier = "vHqD2oFFMh"
weight = 5

[[footer]]
name = ":newspaper_roll: RSS"
pageRef = "index.xml"
identifier = "zNh9Tjq8MD"
weight = 6