# This will be your default build command
[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.125.4"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

# This will be your preview build
[context.dev]
command = "hugo --config config.toml,config-prod.toml --buildFuture --buildDrafts --gc --minify -b $DEPLOY_PRIME_URL"
