name: PSA on New Post!
on:
  push:
    branches:
      - main
    paths:
      - 'content/**.md'
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get the current version
      - uses: actions/checkout@v3
      - name: SendPSA
        uses: StartAutomating/PSA@main
        env:
          AT_PROTOCOL_APP_PASSWORD: ${{ secrets.AT_PROTOCOL_APP_PASSWORD }}
          AT_PROTOCOL_HANDLE: heyitsgilbert.bsky.social
